#!/bin/bash

if [ $# -eq 0 ]; then
  echo "usage: run_quad host_base command*"
  exit 1
fi

for suffix in a b c d
do
	host=$1$suffix.local
	echo
	echo $host':'
	ssh -o StrictHostKeyChecking=no breathecam@$host "${@:2}"
done
